package section2javaintro;

import java.util.Scanner;

public class KeyboardInput {

    public static void main(String[] args) {
        Scanner keyboard = new Scanner(System.in);
        String name;
        String city;
        int age;

        System.out.println("What's your name?");
        // nextLine() consumes the newline character (\n) generated by hitting the
        // enter/return key
        // This means the string of characters in front of the newline character is
        // returned
        // by the method and the newline character is pulled out of the input stream and
        // discarded
        name = keyboard.nextLine();

        System.out.println("What's your age?");
        // nextInt() pulls numeric data representing an integer out of the input stream
        // and ignores the newline character (\n)
        age = keyboard.nextInt();

        // Consume the newline character left in the input stream after pressing enter
        keyboard.nextLine();

        System.out.println("What city do you live in?");
        city = keyboard.nextLine();

        System.out.println("Hello, " + name);
        System.out.println("age is, " + age);
        System.out.println("city is, " + city);

        // Challenge: Real Number Input
        // Write code to prompt the user for a real number
        // Multiply the number by 2
        // Print the resulting value to the console before the name of the city is
        // obtained

        System.out.println("What's your age again?");
        age = keyboard.nextInt();

        System.out.println("What's your real number? ");
        double realNumber = keyboard.nextInt() * 2;
        System.out.println("Your number multiplied by 2 is: " + realNumber);
        keyboard.nextLine();

        System.out.println("What city do you live in again?");
        city = keyboard.nextLine();

        System.out.println("city is, " + city);
    }
}
